# 신경망 (Deep Neural Network)

In [3]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd

## 1. Tensor

**Tensor(텐서)** : 수치형 데이터를 위한 컨테이너입니다. 즉, 임의의 차원 개수를 가지는 행렬의 일반화된 모습입니다(다차원 배열).

### (1) 1D 텐서 : 벡터

In [7]:
x = np.array([12, 3, 6, 14, 7])
print(x)
print('차원 : ', x.ndim)

[12  3  6 14  7]
차원 :  1


### (2) 2D 텐서 : 행렬

In [8]:
x = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]])
print(x)
print('차원 : ', x.ndim)

[[ 5 78  2 34  0]
 [ 6 79  3 35  1]
 [ 7 80  4 36  2]]
차원 :  2


### (3) 3D 텐서 : 고차원 텐서

In [9]:
x = np.array([[[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]]])
print(x)
print('차원 : ', x.ndim)

[[[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]]
차원 :  3


## 2. 신경망의 구조
<img src="./images/dnn_network.png" style="height:200px width:400px">

- 층(layer) : 하나 이상의 텐서를 입력으로 받아 하나 이상의 텐서를 출력하는 데이터 처리 모듈입니다.
- 가중치(weight) : 층의 상태이며, 확률적 경사 하강법에 의해 학습되는 하나 이상의 텐서입니다. 여기에는 네트워크가 학습한 지식이 들어 있습니다.
- 층의 네트워크 : 층을 쌓는 것입니다.
- 손실 함수(목적 함수) : 훈련하는 동안 최소화될 값입니다. 주어진 문제에 대한 성공 지표가 됩니다.
- 옵티마이저 : 손실 함수를 기반으로 네트워크가 어떻게 업데이트될지를 결정합니다. 특정 종류의 확률적 경사 하강법(SGD)을 구현합니다.

## 3. Keras

케라스는 딥러닝 모델을 간편하게 만들고 훈련시킬 수 있는 파이썬을 위한 딥러닝 프레임워크입니다.

케라스의 특징은 다음과 같습니다.
 - 동일한 코드로 CPU와 GPU에서 실행할 수 있습니다.
 - 사용하기 쉬운 API를 가지고 있어 딥러닝 모델의 프로토타입을 빠르게 만들 수 있습니다.
 - 합성곱 신경망, 순환 신경망을 지원하며 이 둘을 자유롭게 조합하여 사용할 수 있습니다.
 - 다중 입력이나, 다중 출력 모델, 층의 공유, 모델 공유 등 어떤 네트워크 구조도 만들 수 있습니다. 이 말은 적대적 생성 신경망부터 뉴럴 튜링 머신까지 케라스는 기본적으로 어떤 딥러닝 모델에도 적합하다는 뜻입니다.
 
구글, 넷플릭스, 우버, 썬, 옐프, 스퀘어 그리고 다양한 분야의 스타트업 수백 개가 케라스를 사용합니다. 머신 러닝 경연 웹사이트인 캐글에서도 케라스의 인기가 높습니다. 최근에 거의 모든 딥러닝 경련 대회의 우승자들이 케라스를 사용하고 있습니다.

<img src="http://snowdeer.github.io/assets/machine-learning/012.jpg" style="height:200px width:400px">

## 4. Keras의 DNN을 이용하여 MNIST 분류하기

In [10]:
from keras.datasets import mnist

In [11]:
(train_images, train_labels), (test_images, test_labels) = \
    mnist.load_data()

In [13]:
print('학습셋 x : ', train_images.shape)
print('학습셋 y : ', train_labels.shape)
print('테스트셋 x : ', test_images.shape)
print('테스트셋 y : ', test_labels.shape)

학습셋 x :  (60000, 28, 28)
학습셋 y :  (60000,)
테스트셋 x :  (10000, 28, 28)
테스트셋 y :  (10000,)
