# 신경망 (Deep Neural Network)

In [3]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd

## 1. Tensor

**Tensor(텐서)** : 수치형 데이터를 위한 컨테이너입니다. 즉, 임의의 차원 개수를 가지는 행렬의 일반화된 모습입니다(다차원 배열).

### (1) 1D 텐서 : 벡터

In [7]:
x = np.array([12, 3, 6, 14, 7])
print(x)
print('차원 : ', x.ndim)

[12  3  6 14  7]
차원 :  1


### (2) 2D 텐서 : 행렬

In [8]:
x = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]])
print(x)
print('차원 : ', x.ndim)

[[ 5 78  2 34  0]
 [ 6 79  3 35  1]
 [ 7 80  4 36  2]]
차원 :  2


### (3) 3D 텐서 : 고차원 텐서

In [9]:
x = np.array([[[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]],
              [[5, 78, 2, 34, 0],
               [6, 79, 3, 35, 1],
               [7, 80, 4, 36, 2]]])
print(x)
print('차원 : ', x.ndim)

[[[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]]
차원 :  3


## 2. 신경망의 구조
<img src="./images/dnn_network.png" style="height:200px width:400px">

- 층(layer) : 하나 이상의 텐서를 입력으로 받아 하나 이상의 텐서를 출력하는 데이터 처리 모듈입니다.
- 가중치(weight) : 층의 상태이며, 확률적 경사 하강법에 의해 학습되는 하나 이상의 텐서입니다. 여기에는 네트워크가 학습한 지식이 들어 있습니다.
- 층의 네트워크 : 층을 쌓는 것입니다.
- 손실 함수(목적 함수) : 훈련하는 동안 최소화될 값입니다. 주어진 문제에 대한 성공 지표가 됩니다.
- 옵티마이저 : 손실 함수를 기반으로 네트워크가 어떻게 업데이트될지를 결정합니다. 특정 종류의 확률적 경사 하강법(SGD)을 구현합니다.

## 3. Keras

케라스는 딥러닝 모델을 간편하게 만들고 훈련시킬 수 있는 파이썬을 위한 딥러닝 프레임워크입니다.

케라스의 특징은 다음과 같습니다.
 - 동일한 코드로 CPU와 GPU에서 실행할 수 있습니다.
 - 사용하기 쉬운 API를 가지고 있어 딥러닝 모델의 프로토타입을 빠르게 만들 수 있습니다.
 - 합성곱 신경망, 순환 신경망을 지원하며 이 둘을 자유롭게 조합하여 사용할 수 있습니다.
 - 다중 입력이나, 다중 출력 모델, 층의 공유, 모델 공유 등 어떤 네트워크 구조도 만들 수 있습니다. 이 말은 적대적 생성 신경망부터 뉴럴 튜링 머신까지 케라스는 기본적으로 어떤 딥러닝 모델에도 적합하다는 뜻입니다.
 
구글, 넷플릭스, 우버, 썬, 옐프, 스퀘어 그리고 다양한 분야의 스타트업 수백 개가 케라스를 사용합니다. 머신 러닝 경연 웹사이트인 캐글에서도 케라스의 인기가 높습니다. 최근에 거의 모든 딥러닝 경련 대회의 우승자들이 케라스를 사용하고 있습니다.

<img src="http://snowdeer.github.io/assets/machine-learning/012.jpg" style="height:200px width:400px">

## 4. Keras의 DNN을 이용하여 MNIST 분류하기
### (1) 데이터 로딩

In [10]:
from keras.datasets import mnist

In [11]:
(train_images, train_labels), (test_images, test_labels) = \
    mnist.load_data()

In [13]:
print('학습셋 x : ', train_images.shape)
print('학습셋 y : ', train_labels.shape)
print('테스트셋 x : ', test_images.shape)
print('테스트셋 y : ', test_labels.shape)

학습셋 x :  (60000, 28, 28)
학습셋 y :  (60000,)
테스트셋 x :  (10000, 28, 28)
테스트셋 y :  (10000,)


In [15]:
train_images[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [16]:
train_labels[0]

5

### (2) DNN 학습
 - 훈련 데이터 train_images, train_labels를 네트워크에 주입
 - 네트워크는 이미지와 레이블을 연관시킬수 있도록 학습됨
 - test_images에 대한 예측을 네트워크에 요청
 - 예측이 train_labels와 맞는지 확인

Layer는 주어진 문제에 더 의미있는 **표현(representation)** 을 입력된 데이터로부터 추출합니다. 대부분의 딥러닝은 간단한 층을 연결하여 구성되어 있고, 점진적으로 데이터를 정제하는 형태를 띄고 있습니다. 딥러닝 모델은 데이터 정제 필터(층)가 연속되어 있는 데이터 프로세싱을 위한 여과기와 같습니다.

> 네트워크 구성

In [ ]:
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28*28, )))
network.add(layers.Dense(10, activation='softmax'))

첫번째 층은 input이 784 차원이고, output이 512차원입니다.

마지막 층은 10개의 확률 점수가 들어 있는 배열을 반환하는 **softmax(소프트맥스)** 층입니다. 각 점수는 현재 숫자 이미지가 10개의 숫자 클래스 중 하나에 속할 확률입니다.

> 훈련을 위한 컴파일

 - 손실 함수(loss function) : 훈련 데이터에서 신경망의 성능을 측정하는 방법으로 네트워크가 옳은 방향으로 학습될 수 있도록 도와줍니다.
 - 옵티마이저(optimizer) : 입력된 데이터와 손실 함수를 기반으로 네트워크를 업데이트하는 메커니즘입니다.
 - 훈련과 테스트 과정을 모니터링할 지표 : 여기에서는 정확도(정확히 분류된 이미지의 비율)만 고려하겠습니다.

In [18]:
network.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

> 데이터 스케일링

In [19]:
# 훈련을 시작하기 전에 모든 값을 0과 1 사이로 스케일을 조정
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [20]:
# 레이블
from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [22]:
train_labels[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [23]:
print(train_labels.shape)
print(test_labels.shape)

(60000, 10)
(10000, 10)


> 훈련

In [24]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 5s 91us/step - loss: 0.2568 - acc: 0.9245
Epoch 2/5
60000/60000 [==============================] - 5s 84us/step - loss: 0.1036 - acc: 0.9693
Epoch 3/5
60000/60000 [==============================] - 5s 78us/step - loss: 0.0679 - acc: 0.9803
Epoch 4/5
60000/60000 [==============================] - 5s 79us/step - loss: 0.0492 - acc: 0.9857
Epoch 5/5
60000/60000 [==============================] - 5s 78us/step - loss: 0.0368 - acc: 0.9886


In [25]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

10000/10000 [==============================] - 1s 62us/step


In [26]:
print('test_acc', test_acc)

test_acc 0.9783


In [27]:
network.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_2 (Dense)              (None, 10)                5130      
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


## 5. Keras의 DNN을 이용하여 영화 리뷰 분류하기

인터넷 영화 데이터베이스(internet movie database)로부터 가져온 리뷰 5만 개로 이루어진 IMDB 데이터셋을 이용하여 DNN 분류기를 생성하겠습니다.

### (1) IMDB 데이터셋 로딩

In [28]:
from keras.datasets import imdb

# 훈련 데이터에서 가장 자주 나타나는 단어 1만 개만 사용한다.
(train_data, train_labels), (test_data, test_labels) = \
    imdb.load_data(num_words=10000)

In [34]:
print(train_data[0])

[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]


In [35]:
train_labels[0]

1

각 단어는 id를 가지고 있습니다. id를 이용하여 리뷰를 문장으로 바꾸어 봅니다.

In [40]:
word_index = imdb.get_word_index()
# Word index는 dict입니다.
list(word_index.items())[:5]

[('fawn', 34701),
 ('tsukino', 52006),
 ('nunnery', 52007),
 ('sonja', 16816),
 ('vani', 63951)]

In [41]:
reverse_word_index = dict(
    [(value, key) for (key, value) in word_index.items()]
)
list(reverse_word_index.items())[:5]

[(34701, 'fawn'),
 (52006, 'tsukino'),
 (52007, 'nunnery'),
 (16816, 'sonja'),
 (63951, 'vani')]

In [58]:
# 리뷰를 디코딩한다. 0, 1, 2는 패딩/문서시작/사전에 없을을 위한 인덱스이기 때문에 3을 빼줌
decode_review = ' '.join(
    [reverse_word_index.get(i - 3, '?') for i in train_data[0]]
)
decode_review

"? this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert ? is an amazing actor and now the same being director ? father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for ? and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also ? to the two little boy's that played the ? of norman and paul they were just brilliant children are often left out of the ? list i think because the stars that play them all grown up are such a big profile for the whole film but these children are amazing and should be praised for what they have done don't you th